### ISSUE TITLE
Replicating / documenting the Link plugin representation in Text plugin

### ISSUE THREAD

**Issue by frnhr** [jrief/djangocms-cascade#163]
There seems to be some very interesting magic going on that is undocumented.

How do you achieve the representation of Link plugin in CKEditor field of the Text plugin? In the source  mode of CKEditor (the HTML mode), the Link plugins are represented as usual `<img alt="Link" id="plugin_obj_1234"...` but in the actual WYSIWYG editor, that is arcanomagically changed to `<a href="#" id="plugin_obj_4132"...`. 

That is awesome! But seems to be completely undocumented. Is it possible to replicate this, i.e. reuse it in a custom cascade plugin?

Looking at the code left me no smarter. I think it has something to do with _rings_ in JS o_O
Wasn't smart enough to figure it out though. Any hints?

**Comment by frnhr** [comment]
Ah, found it:
https://github.com/divio/djangocms-text-ckeditor/pull/71/files#diff-95970cff1bf01f88bb2722d06a6e8592R215

Also ref: https://github.com/divio/djangocms-text-ckeditor/issues/285

In short, this feature is specific to plugins of type "Link", hardcoded in JS, and outside of cms-cascade. So waiting for better days I guess... Kinda sad :(

**Comment by jrief** [comment]
Please also check this one: https://github.com/divio/djangocms-text-ckeditor/issues/143

It unfortunately was closed unresolved. I still believe that we should replace that hacky <img>-tag. It a) would allow us to use beautifulsoup instead of a regex and b) would allow a much cleaner implementation in the CKeditor's JS plugin.
