### ISSUE TITLE
LinkForm doesn't play well with translations

### ISSUE THREAD

**Issue by rfleschenberg** [jrief/djangocms-cascade#173]
- a CMS page exists in English (default language) and German
- User edits the German version and uses the link plugin to add a link to another CMS page
- Expected result: user sees the German pages in the select widget
- Actual result: user sees the English pages in the select widget

The link will later point correctly at the German page, but the UI is confusing.

**Comment by jrief** [comment]
Just tested this again.
The problem here is, that there are two settings for the language.
1. Is the language for the frontend view. This is done in the CMS toolbar in the **Language** settings.
2. Is the langue for the admin. This is done the CMS toolbar in the **Project > User settings... > Language**. If you change that, you get the page title in the correct language.

Therefore, this is not a bug, but a feature – a CMS feature, btw.
