### ISSUE TITLE
per-plugin css or free form css styles

### ISSUE THREAD

**Issue by miraculixx** [jrief/djangocms-cascade#179]
djangocms-cascade is great! 

One issue I have is that my designers would like to add per-plugin css styles without using a style wrapper - wrappers tend to blow up the page structure. 

The idea is as follows:

* in each plugin there is an InlineForm or a "css tab" (much like the "advanced settings" on a page)
* the form provides an entry field to add css styles (as in a style sheet, e.g. `.mystyle { .... }` 
* if present, the plugin automatically wraps the plugin's template

This should work for any cascade plugin without modifying any of its templates or adding new plugins. What would be the best approach to accomplish this? Thank you.

**Comment by jrief** [comment]
Just for clarity, what do you mean by style wrapper?
Did you have a look at the extra_fields options, there you can configure
quite easily which styles are allowed.

Am 02.09.2016 12:32 schrieb "miraculixx" <notifications@github.com>:

**Comment by miraculixx** [comment]
Yes I looked at extra_fields options. I think it's great for non-tech users but it seems somewhat restrictive and doesn't quite fit my (designer's) need. The requirement is to add ad-hoc styles on a per-page basis, and attach these styles to arbitrary plugins on that page.

I have already implemented a CSSStyle plugin (as a CascadePlugin) so ad-hoc styles can now be added by using this plugin. What I would like to do next is to provide an entry field on any other cascade plugin, much like extra_fields does, that is rendered as a wrapper to the plugin's template with the `class` attribute set accordingly. 

e.g. the CSSStyle plugin renders the following styles:

```
.mystyle { ... }
```

on say a container or a row plugin we have an entry field as follows:

```
# plugin form
(...)
classes: mystyle_______
```

and this gets rendered as 

```
<div class="mystyle">  <== this is the wrapper that I meant
   <... plugin's actual rendered html ...>
</div>
```

The parts that I can't figure out are:

1.  how to add the `classes` entry field to any and all plugin forms, at best without modifying any code. extra fields seems to do this somehow but I'm not sure if that mechanism can be used by custom plugins too.
2. how to wrap the plugin's rendered html.  I know it can be done adding a plugin that wraps other plugins, and this should achieve the same effect, but without adding a wrapper first...

**Comment by jrief** [comment]
Ah!
There is a SimpleWrapper Plugin, and you can configure it to accept any
number of CSS classes.
If that's not enough, try the CustomSnippet Plugin.
In 0.10 extra fields can be configured through settings.py

Am 02.09.2016 19:08 schrieb "miraculixx" <notifications@github.com>:

Yes I looked at extra_fields options. I think it's great for non-tech users
but it seems somewhat restrictive and doesn't quite fit my (designer's)
need. The requirement is to add ad-hoc styles on a per-page basis, and
attach these styles to arbitrary plugins on that page.

I have already implemented a CSSStyle plugin (as a CascadePlugin) so ad-hoc
styles can now be added by using this plugin. What I would like to do next
is to provide an entry field on any other cascade plugin, much like
extra_fields does, that is rendered as a wrapper to the plugin's template
with the class attribute set accordingly.

e.g. the CSSStyle plugin renders the following styles:

.mystyle { ... }

on say a container or a row plugin we have an entry field as follows:

# plugin form
(...)
classes: mystyle_______

and this gets rendered as

<div class="mystyle">  <== this is the wrapper that I meant
   <... plugin's actual rendered html ...>
</div>

The parts that I can't figure out are:

   1. how to add the classes entry field to any and all plugin forms, at
   best without modifying any code. extra fields seems to do this somehow but
   I'm not sure if that mechanism can be used by custom plugins too.
   2. how to wrap the plugin's rendered html. I know it can be done adding
   a plugin that wraps other plugins, and this should achieve the same effect,
   but without adding a wrapper first...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jrief/djangocms-cascade/issues/179#issuecomment-244433149>,
or mute the thread

**Comment by jrief** [comment]
Just another question.
Do your designers (want to) add CSS styles, writing their own classes using a plain text editor?

**Comment by jrief** [comment]
Just to come back to your ideas

> in each plugin there is an InlineForm or a "css tab" (much like the "advanced settings" on a page)

well it's not a tab, but appended to the bottom of each plugin editor (could be changed tough).

> the form provides an entry field to add css styles (as in a style sheet, e.g. .mystyle { .... }

if a plugin is configured to accept extra CSS classes, then there is a checkbox for each class. The user then can select some of them.

> if present, the plugin automatically wraps the plugin's template

you can configure a plugin to accept alternative rendering templates. They can be part of your project and they can optionally be shipped with their own styles.

Can I close this issue?

**Comment by miraculixx** [comment]
thank you for your feedbacks! Unfortunately I missed the ones from 15 days back, still good to know. 

> Can I close this issue?

yes, thank you.
